spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    suffix: .ftl
  sitemesh:
    decorator:
      metaTag: layout
      mappings:
        - path: /*
          decorator: /layouts/decorator.html
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
#    whitelabel:
#      enabled: false
