spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    suffix: .ftl
  sitemesh:
    decorator:
      metaTag: layout
      mappings:
        - path: /*
          decorator: /layouts/decorator.html