spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    suffix: .ftl
sitemesh:
  decorator:
    metaTag: decorator
#    tagRuleBundles: org.sitemesh.content.tagrules.html.Sm2TagRuleBundle
    exclusions: /assets/*
    mappings:
      - path: /*
        decorator: default.html
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
#    whitelabel:
#      enabled: false
